package demo

import (
	"time"

	"github.com/kiyohara/slapex/internal/slack"
)

// ScenarioEN is the English sample: the fictional open tech community Agent Lab
// — students and early-career engineers sharing know-how about AI agents —
// prepares its meetup event "Agent Night vol. 3". It mirrors the Japanese
// scenario's pattern coverage (see ScenarioJA), except the deleted (tombstone)
// message: its replacement text is currently rendered in Japanese by the
// exporter, so it is shown in the Japanese sample only.
func ScenarioEN(now time.Time) *Scenario {
	day1 := now.AddDate(0, 0, -2)
	day2 := now.AddDate(0, 0, -1)

	assets := map[string]Asset{
		"/files/workspace-icon.svg": workspaceIconSVG("#5f3dc4", "#d6336c"),
		"/files/avatar-alice.svg":   avatarSVG("A", "#e8590c"),
		"/files/avatar-ben.svg":     avatarSVG("B", "#1971c2"),
		"/files/avatar-chika.svg":   avatarSVG("C", "#0ca678"),
		"/files/avatar-dan.svg":     avatarSVG("D", "#7048e8"),
		"/files/emoji-ship-it.svg":  badgeEmojiSVG([]string{"SHIP", "IT!"}, "#1971c2", 20),
		"/files/emoji-comet.svg":    cometEmojiSVG(),
		"/files/banner-art.svg":     packageArtSVG("AGENT NIGHT", "vol. 3 / Agent Lab"),
		"/files/banner-thumb.svg":   packageArtSVG("AGENT NIGHT", "vol. 3 / Agent Lab"),
		"/files/chart-eval.svg":     chartSVG("Demo agent scores (out of 100)", []string{"Search", "Summary", "Codegen", "Chat"}, []int{92, 88, 95, 74}, "#845ef7"),
		"/files/chart-thumb.svg":    chartSVG("Demo agent scores (out of 100)", []string{"Search", "Summary", "Codegen", "Chat"}, []int{92, 88, 95, 74}, "#845ef7"),
		"/files/news-icon.svg":      serviceIconSVG("S", "#c92a2a"),
		"/files/news-og.svg":        ogImageSVG("SAMPLE TECH", "The AI agent meetup grows", "#343a40", "#1d2b53"),
		"/files/meetup-runbook.pdf": samplePDF([]string{
			"Agent Night vol.3 - Staff Runbook (sample)",
			"1. Open the venue at 18:30",
			"2. Livestream check at 19:00",
			"3. Share photos in the event channel",
			"Generated by the slapex sample fixture",
		}),
	}

	threadTS := ts(at(day2, 9, 40, 0))
	threadParent := slack.Message{
		Type:       "message",
		TS:         threadTS,
		ThreadTS:   threadTS,
		User:       "U01ALICE",
		Text:       "Demo agent eval results are in — details in this thread :thread:",
		ReplyCount: 4,
		Reactions:  []slack.Reaction{{Name: "eyes", Count: 3}},
	}

	return &Scenario{
		Lang:        "en",
		ChannelName: "agent-night-vol3",
		Auth: slack.AuthTest{
			URL:    "https://agent-lab.example.slack.com/",
			Team:   "Agent Lab",
			TeamID: "TAGLAB0001",
			User:   "slapex",
			UserID: "USLAPEX01",
			BotID:  "BSLAPEX01",
		},
		TeamInfo: &slack.TeamInfo{
			ID:     "TAGLAB0001",
			Name:   "Agent Lab",
			Domain: "agent-lab",
			Icon:   slack.TeamIcon{Image68: "{{base}}/files/workspace-icon.svg"},
		},
		Channels: []slack.Channel{
			{ID: "C00ANNOUNC", Name: "announcements", IsMember: true},
			{ID: "C01EVENT01", Name: "agent-night-vol3", IsMember: true},
		},
		Users: map[string]slack.User{
			"U01ALICE": sampleUser("U01ALICE", "alice", "Alice Rivera", "Alice", "{{base}}/files/avatar-alice.svg"),
			"U02BEN":   sampleUser("U02BEN", "ben", "Ben Carter", "Ben", "{{base}}/files/avatar-ben.svg"),
			"U03CHIKA": sampleUser("U03CHIKA", "chika", "Chika Ito", "Chika", "{{base}}/files/avatar-chika.svg"),
			"U04DAN":   sampleUser("U04DAN", "dan", "Dan Kim", "Dan", "{{base}}/files/avatar-dan.svg"),
		},
		Emoji: map[string]string{
			"ship_it": "{{base}}/files/emoji-ship-it.svg",
			"comet":   "{{base}}/files/emoji-comet.svg",
		},
		Messages: []slack.Message{
			{
				Type: "message", Subtype: "channel_join",
				TS: ts(at(day1, 9, 0, 0)), User: "U01ALICE",
				Text: "<@U01ALICE> has joined the channel",
			},
			{
				Type: "message", Subtype: "channel_join",
				TS: ts(at(day1, 9, 2, 0)), User: "U02BEN", Inviter: "U01ALICE",
				Text: "<@U02BEN> has joined the channel",
			},
			{
				Type: "message", Subtype: "channel_topic",
				TS: ts(at(day1, 9, 5, 0)), User: "U01ALICE",
				Text: "<@U01ALICE> set the channel topic: Agent Night vol. 3 — meetup prep :robot_face:",
			},
			{
				Type: "message",
				TS:   ts(at(day1, 9, 12, 0)), User: "U01ALICE",
				Text: "*Agent Night vol. 3 is officially on!* :tada:\n" +
					"Date: *Friday, July 18*, same coworking space as last time. Details live in <https://example.com/wiki/agent-night-vol3|the event wiki>.\n" +
					"Sign-up announcements go to <#C00ANNOUNC|announcements>. Questions → this channel or ping <@U02BEN>. <!here>",
				Reactions: []slack.Reaction{
					{Name: "tada", Count: 4},
					{Name: "comet", Count: 2},
					{Name: "raised_hands", Count: 2},
				},
			},
			{
				Type: "message",
				TS:   ts(at(day1, 9, 30, 0)), User: "U02BEN",
				Text: "To-dos for this week:\n" +
					"• ~Book the venue~ :white_check_mark:\n" +
					"• Publish the sign-up page (`/events/vol3`)\n" +
					"• Announce the call for lightning talks\n" +
					"Then:\n" +
					"1. Livestream rehearsal\n" +
					"2. Assign day-of roles",
				Edited:    editedAt(at(day1, 9, 47, 0)),
				Reactions: []slack.Reaction{{Name: "+1", Count: 3}},
			},
			{
				Type: "message", Subtype: "file_share",
				TS: ts(at(day1, 10, 15, 0)), User: "U03CHIKA",
				Text: "First pass at the event banner :art: feedback welcome!",
				Files: []slack.File{{
					ID:                 "F01BANNER",
					Name:               "banner-v1.svg",
					Mimetype:           "image/svg+xml",
					Size:               int64(len(assets["/files/banner-art.svg"].Body)),
					URLPrivateDownload: "{{base}}/files/banner-art.svg",
					Thumb360:           "{{base}}/files/banner-thumb.svg",
				}},
				Reactions: []slack.Reaction{
					{Name: "heart", Count: 3},
					{Name: "eyes", Count: 2},
				},
			},
			{
				Type: "message",
				TS:   ts(at(day1, 11, 2, 0)), User: "U04DAN",
				Text: "Agent Lab got a write-up in the tech press :newspaper:\n<https://example.com/news/agent-lab>",
				Attachments: []slack.Attachment{{
					ServiceName: "Sample Tech",
					ServiceIcon: "{{base}}/files/news-icon.svg",
					Title:       "Student-led AI agent meetup keeps growing",
					TitleLink:   "https://example.com/news/agent-lab",
					Text:        "The open community for sharing AI agent know-how keeps drawing students and early-career engineers. <@U03CHIKA>'s event banner gets a mention too.",
					ImageURL:    "{{base}}/files/news-og.svg",
				}},
			},
			threadParent,
			{
				Type: "message",
				TS:   ts(at(day2, 11, 30, 0)), User: "U02BEN",
				Text: "Event site is green on staging:\n" +
					"```$ agentlab deploy --target staging\nOK  build 412 (38s)\nOK  smoke tests 12/12```\n" +
					"Prod is one `agentlab deploy --target prod` away once the program is final.",
			},
			{
				Type: "message", Subtype: "bot_message",
				TS:    ts(at(day2, 11, 31, 0)),
				BotID: "B01DEPLOY", Username: "DeployBot", BotProfile: botProfile("DeployBot"),
				Text:      "Deployed *agent-night-site* v1.4.0 to staging :package:",
				Reactions: []slack.Reaction{{Name: "ship_it", Count: 3}},
			},
			{
				Type: "message", Subtype: "me_message",
				TS: ts(at(day2, 12, 20, 0)), User: "U04DAN",
				Text: "is printing 100 stickers for the meetup",
			},
			{
				Type: "message", Subtype: "file_share",
				TS: ts(at(day2, 13, 5, 0)), User: "U01ALICE",
				Text: "Final staff runbook for the meetup :clipboard: staff, please skim it before the day.",
				Files: []slack.File{{
					ID:                 "F02RUNBOOK",
					Name:               "meetup-runbook.pdf",
					Mimetype:           "application/pdf",
					Size:               int64(len(assets["/files/meetup-runbook.pdf"].Body)),
					URLPrivateDownload: "{{base}}/files/meetup-runbook.pdf",
				}},
				Reactions: []slack.Reaction{{Name: "+1", Count: 2}},
			},
			{
				Type: "message",
				TS:   ts(at(day2, 15, 5, 0)), User: "U03CHIKA",
				Text: "Wrapping up for today — see everyone at Agent Night :sparkles:",
				Reactions: []slack.Reaction{
					{Name: "wave", Count: 3},
				},
			},
		},
		Replies: map[string][]slack.Message{
			threadTS: {
				threadParent,
				{
					Type: "message",
					TS:   ts(at(day2, 9, 44, 0)), ThreadTS: threadTS, User: "U02BEN",
					Text: "Task success rate is up *+12pt* from the last build :chart_with_upwards_trend: breakdown below",
				},
				{
					Type: "message", Subtype: "file_share",
					TS: ts(at(day2, 9, 51, 0)), ThreadTS: threadTS, User: "U03CHIKA",
					Text: "Plotted the per-task scores:",
					Files: []slack.File{{
						ID:                 "F03CHART",
						Name:               "demo-eval-scores.svg",
						Mimetype:           "image/svg+xml",
						Size:               int64(len(assets["/files/chart-eval.svg"].Body)),
						URLPrivateDownload: "{{base}}/files/chart-eval.svg",
						Thumb360:           "{{base}}/files/chart-thumb.svg",
					}},
					Reactions: []slack.Reaction{{Name: "ship_it", Count: 2}},
				},
				{
					Type: "message",
					TS:   ts(at(day2, 10, 3, 0)), ThreadTS: threadTS, User: "U04DAN",
					Text: "&gt; Task success rate is up +12pt from the last build\nThat number goes on the opening slide. Nice work <@U02BEN>!",
				},
				{
					Type: "message",
					TS:   ts(at(day2, 10, 10, 0)), ThreadTS: threadTS, User: "U01ALICE",
					Text: "Locking the demo setup, then. Thanks everyone! :tada:",
				},
			},
		},
		Assets: assets,
	}
}
