package main

import (
	"time"

	"github.com/kiyohara/slapex/internal/slack"
)

// scenarioEN is the English sample: the fictional company Acme Rocketry
// prepares the launch of a model rocket kit. It mirrors the Japanese
// scenario's pattern coverage (see scenarioJA), except the deleted
// (tombstone) message: its replacement text is currently rendered in
// Japanese by the exporter, so it is shown in the Japanese sample only.
func scenarioEN(now time.Time) *scenario {
	day1 := now.AddDate(0, 0, -2)
	day2 := now.AddDate(0, 0, -1)

	assets := map[string]sampleAsset{
		"/files/workspace-icon.svg": workspaceIconSVG("#5f3dc4", "#d6336c"),
		"/files/avatar-alice.svg":   avatarSVG("A", "#e8590c"),
		"/files/avatar-ben.svg":     avatarSVG("B", "#1971c2"),
		"/files/avatar-chika.svg":   avatarSVG("C", "#0ca678"),
		"/files/avatar-dan.svg":     avatarSVG("D", "#7048e8"),
		"/files/emoji-ship-it.svg":  badgeEmojiSVG([]string{"SHIP", "IT!"}, "#1971c2", 20),
		"/files/emoji-comet.svg":    cometEmojiSVG(),
		"/files/package-art.svg":    packageArtSVG("COMET MINI", "Model Rocket Kit / Acme Rocketry"),
		"/files/package-thumb.svg":  packageArtSVG("COMET MINI", "Model Rocket Kit / Acme Rocketry"),
		"/files/chart-drag.svg":     chartSVG("Wind tunnel drag by run (counts)", []string{"Run 1", "Run 2", "Run 3", "Run 4"}, []int{118, 112, 104, 96}, "#845ef7"),
		"/files/chart-thumb.svg":    chartSVG("Wind tunnel drag by run (counts)", []string{"Run 1", "Run 2", "Run 3", "Run 4"}, []int{118, 112, 104, 96}, "#845ef7"),
		"/files/news-icon.svg":      serviceIconSVG("S", "#c92a2a"),
		"/files/news-og.svg":        ogImageSVG("SAMPLE NEWS", "Acme teases the Comet Mini", "#343a40", "#1d2b53"),
		"/files/launch-runbook.pdf": samplePDF([]string{
			"Comet Mini - Launch Day Runbook (sample)",
			"1. Open the range at 09:00",
			"2. Check the weather every hour",
			"3. Share photos in the launch channel",
			"Generated by the slapex sample fixture",
		}),
	}

	threadTS := ts(at(day2, 9, 40, 0))
	threadParent := slack.Message{
		Type:       "message",
		TS:         threadTS,
		ThreadTS:   threadTS,
		User:       "U01ALICE",
		Text:       "Wind tunnel results are in — details in this thread :thread:",
		ReplyCount: 4,
		Reactions:  []slack.Reaction{{Name: "eyes", Count: 3}},
	}

	return &scenario{
		Lang:        "en",
		ChannelName: "comet-mini-launch",
		Auth: slack.AuthTest{
			URL:    "https://acme-rocketry.example.slack.com/",
			Team:   "Acme Rocketry",
			TeamID: "TACME0001",
			User:   "slapex",
			UserID: "USLAPEX01",
			BotID:  "BSLAPEX01",
		},
		TeamInfo: &slack.TeamInfo{
			ID:     "TACME0001",
			Name:   "Acme Rocketry",
			Domain: "acme-rocketry",
			Icon:   slack.TeamIcon{Image68: "{{base}}/files/workspace-icon.svg"},
		},
		Channels: []slack.Channel{
			{ID: "C00GENERAL", Name: "general", IsMember: true},
			{ID: "C01COMET01", Name: "comet-mini-launch", IsMember: true},
		},
		Users: map[string]slack.User{
			"U01ALICE": sampleUser("U01ALICE", "alice", "Alice Rivera", "Alice", "{{base}}/files/avatar-alice.svg"),
			"U02BEN":   sampleUser("U02BEN", "ben", "Ben Carter", "Ben", "{{base}}/files/avatar-ben.svg"),
			"U03CHIKA": sampleUser("U03CHIKA", "chika", "Chika Ito", "Chika", "{{base}}/files/avatar-chika.svg"),
			"U04DAN":   sampleUser("U04DAN", "dan", "Dan Kim", "Dan", "{{base}}/files/avatar-dan.svg"),
		},
		Emoji: map[string]string{
			"ship_it": "{{base}}/files/emoji-ship-it.svg",
			"comet":   "{{base}}/files/emoji-comet.svg",
		},
		Messages: []slack.Message{
			{
				Type: "message", Subtype: "channel_join",
				TS: ts(at(day1, 9, 0, 0)), User: "U01ALICE",
				Text: "<@U01ALICE> has joined the channel",
			},
			{
				Type: "message", Subtype: "channel_join",
				TS: ts(at(day1, 9, 2, 0)), User: "U02BEN", Inviter: "U01ALICE",
				Text: "<@U02BEN> has joined the channel",
			},
			{
				Type: "message", Subtype: "channel_topic",
				TS: ts(at(day1, 9, 5, 0)), User: "U01ALICE",
				Text: "<@U01ALICE> set the channel topic: Comet Mini — launch prep :rocket:",
			},
			{
				Type: "message",
				TS:   ts(at(day1, 9, 12, 0)), User: "U01ALICE",
				Text: "*Comet Mini launch prep starts today!* :tada:\n" +
					"Target date: *Friday, July 18*. Docs live in <https://example.com/wiki/comet-mini|the launch wiki>.\n" +
					"Company-wide announcements go to <#C00GENERAL|general>. Questions → this channel or ping <@U02BEN>. <!here>",
				Reactions: []slack.Reaction{
					{Name: "tada", Count: 4},
					{Name: "comet", Count: 2},
					{Name: "raised_hands", Count: 2},
				},
			},
			{
				Type: "message",
				TS:   ts(at(day1, 9, 30, 0)), User: "U02BEN",
				Text: "Launch checklist (week 1):\n" +
					"• ~Finalize the fin spec~ :white_check_mark:\n" +
					"• Order `v0.9.3` box labels\n" +
					"• Book the wind tunnel for Thursday\n" +
					"Then:\n" +
					"1. Dry run with the launch crew\n" +
					"2. Full dress rehearsal",
				Edited:    editedAt(at(day1, 9, 47, 0)),
				Reactions: []slack.Reaction{{Name: "+1", Count: 3}},
			},
			{
				Type: "message", Subtype: "file_share",
				TS: ts(at(day1, 10, 15, 0)), User: "U03CHIKA",
				Text: "First pass at the package design :art: feedback welcome!",
				Files: []slack.File{{
					ID:                 "F01PKG",
					Name:               "package-design-v1.svg",
					Mimetype:           "image/svg+xml",
					Size:               int64(len(assets["/files/package-art.svg"].Body)),
					URLPrivateDownload: "{{base}}/files/package-art.svg",
					Thumb360:           "{{base}}/files/package-thumb.svg",
				}},
				Reactions: []slack.Reaction{
					{Name: "heart", Count: 3},
					{Name: "eyes", Count: 2},
				},
			},
			{
				Type: "message",
				TS:   ts(at(day1, 11, 2, 0)), User: "U04DAN",
				Text: "The local paper already picked us up :newspaper:\n<https://example.com/news/comet-mini-teaser>",
				Attachments: []slack.Attachment{{
					ServiceName: "Sample News",
					ServiceIcon: "{{base}}/files/news-icon.svg",
					Title:       "Acme Rocketry teases its smallest kit yet",
					TitleLink:   "https://example.com/news/comet-mini-teaser",
					Text:        "The hobby-rocket maker says the Comet Mini will fly this summer. <@U03CHIKA>'s package art is already turning heads.",
					ImageURL:    "{{base}}/files/news-og.svg",
				}},
			},
			threadParent,
			{
				Type: "message",
				TS:   ts(at(day2, 11, 30, 0)), User: "U02BEN",
				Text: "Staging deploy for the launch site is green:\n" +
					"```$ acme deploy --target staging\nOK  build 412 (38s)\nOK  smoke tests 12/12```\n" +
					"Prod is one `acme deploy --target prod` away once content is final.",
			},
			{
				Type: "message", Subtype: "bot_message",
				TS:    ts(at(day2, 11, 31, 0)),
				BotID: "B01LAUNCH", Username: "LaunchBot", BotProfile: botProfile("LaunchBot"),
				Text:      "Deployed *comet-mini-site* v1.4.0 to staging :package:",
				Reactions: []slack.Reaction{{Name: "ship_it", Count: 3}},
			},
			{
				Type: "message", Subtype: "me_message",
				TS: ts(at(day2, 12, 20, 0)), User: "U04DAN",
				Text: "is off to print 500 launch-day flyers",
			},
			{
				Type: "message", Subtype: "file_share",
				TS: ts(at(day2, 13, 5, 0)), User: "U01ALICE",
				Text: "Final launch-day runbook :clipboard: print one for the field box.",
				Files: []slack.File{{
					ID:                 "F02RUNBOOK",
					Name:               "launch-runbook.pdf",
					Mimetype:           "application/pdf",
					Size:               int64(len(assets["/files/launch-runbook.pdf"].Body)),
					URLPrivateDownload: "{{base}}/files/launch-runbook.pdf",
				}},
				Reactions: []slack.Reaction{{Name: "+1", Count: 2}},
			},
			{
				Type: "message",
				TS:   ts(at(day2, 15, 5, 0)), User: "U03CHIKA",
				Text: "Wrapping up for today — see everyone at the rehearsal :sparkles:",
				Reactions: []slack.Reaction{
					{Name: "wave", Count: 3},
				},
			},
		},
		Replies: map[string][]slack.Message{
			threadTS: {
				threadParent,
				{
					Type: "message",
					TS:   ts(at(day2, 9, 44, 0)), ThreadTS: threadTS, User: "U02BEN",
					Text: "Drag is down *8%* from the last prototype :chart_with_downwards_trend: breakdown below",
				},
				{
					Type: "message", Subtype: "file_share",
					TS: ts(at(day2, 9, 51, 0)), ThreadTS: threadTS, User: "U03CHIKA",
					Text: "Plotted the runs:",
					Files: []slack.File{{
						ID:                 "F03CHART",
						Name:               "wind-tunnel-runs.svg",
						Mimetype:           "image/svg+xml",
						Size:               int64(len(assets["/files/chart-drag.svg"].Body)),
						URLPrivateDownload: "{{base}}/files/chart-drag.svg",
						Thumb360:           "{{base}}/files/chart-thumb.svg",
					}},
					Reactions: []slack.Reaction{{Name: "ship_it", Count: 2}},
				},
				{
					Type: "message",
					TS:   ts(at(day2, 10, 3, 0)), ThreadTS: threadTS, User: "U04DAN",
					Text: "&gt; Drag is down 8% from the last prototype\nPutting that number on the landing page. Nice work <@U02BEN>!",
				},
				{
					Type: "message",
					TS:   ts(at(day2, 10, 10, 0)), ThreadTS: threadTS, User: "U01ALICE",
					Text: "Locking the fin design, then. Thanks everyone! :tada:",
				},
			},
		},
		Assets: assets,
	}
}
