package main

import (
	"time"

	"github.com/kiyohara/slapex/internal/slack"
)

// scenarioJA is the Japanese sample: the fictional open tech community
// エージェントラボ — students and early-career engineers sharing know-how
// about AI agents — prepares its meetup event "エージェントナイト vol.3".
// Every name, user and asset is invented for this fixture; nothing comes
// from a real workspace.
//
// Pattern coverage: system messages (join / invited join / topic), mrkdwn
// decorations (bold / strike / inline code / code block / quote / lists /
// labeled and bare links / user / channel / @here mentions), standard and
// custom emoji, reactions, an edited message, a thread with four
// participants, an inline image upload, a URL unfurl with preview image, a
// PDF attachment, a bot message, a /me message and a deleted (tombstone)
// message.
func scenarioJA(now time.Time) *scenario {
	day1 := now.AddDate(0, 0, -2)
	day2 := now.AddDate(0, 0, -1)

	assets := map[string]sampleAsset{
		"/files/workspace-icon.svg": workspaceIconSVG("#0b7285", "#1971c2"),
		"/files/avatar-hikari.svg":  avatarSVG("ひ", "#e8590c"),
		"/files/avatar-ren.svg":     avatarSVG("レ", "#1971c2"),
		"/files/avatar-sakura.svg":  avatarSVG("さ", "#0ca678"),
		"/files/avatar-daichi.svg":  avatarSVG("だ", "#7048e8"),
		"/files/emoji-yatta.svg":    badgeEmojiSVG([]string{"やった"}, "#f08c00", 19),
		"/files/emoji-kansha.svg":   badgeEmojiSVG([]string{"感謝"}, "#e03131", 26),
		"/files/banner-art.svg":     packageArtSVG("エージェントナイト", "vol.3 / エージェントラボ"),
		"/files/banner-thumb.svg":   packageArtSVG("エージェントナイト", "vol.3 / エージェントラボ"),
		"/files/chart-eval.svg":     chartSVG("デモエージェント評価(100点満点)", []string{"検索", "要約", "コード生成", "対話"}, []int{92, 88, 95, 74}, "#845ef7"),
		"/files/chart-thumb.svg":    chartSVG("デモエージェント評価(100点満点)", []string{"検索", "要約", "コード生成", "対話"}, []int{92, 88, 95, 74}, "#845ef7"),
		"/files/news-icon.svg":      serviceIconSVG("サ", "#c92a2a"),
		"/files/news-og.svg":        ogImageSVG("SAMPLE TECH", "広がる AI エージェント勉強会", "#343a40", "#1d2b53"),
		"/files/unei-manual.pdf": samplePDF([]string{
			"Agent Night vol.3 - Staff Runbook (sample)",
			"1. Open the venue at 18:30",
			"2. Livestream check at 19:00",
			"3. Share photos in the event channel",
			"Generated by the slapex sample fixture",
		}),
	}

	threadTS := ts(at(day2, 9, 40, 0))
	threadParent := slack.Message{
		Type:       "message",
		TS:         threadTS,
		ThreadTS:   threadTS,
		User:       "U01HIKARI",
		Text:       "LT 用デモエージェントの評価結果が出ました。詳細はこのスレッドにまとめます :thread:",
		ReplyCount: 4,
		Reactions:  []slack.Reaction{{Name: "eyes", Count: 3}},
	}

	return &scenario{
		Lang:        "ja",
		ChannelName: "エージェントナイト-vol3",
		Auth: slack.AuthTest{
			URL:    "https://agent-lab-jp.example.slack.com/",
			Team:   "エージェントラボ",
			TeamID: "TAGLABJP01",
			User:   "slapex",
			UserID: "USLAPEX01",
			BotID:  "BSLAPEX01",
		},
		TeamInfo: &slack.TeamInfo{
			ID:     "TAGLABJP01",
			Name:   "エージェントラボ",
			Domain: "agent-lab-jp",
			Icon:   slack.TeamIcon{Image68: "{{base}}/files/workspace-icon.svg"},
		},
		Channels: []slack.Channel{
			{ID: "C00NEWS001", Name: "お知らせ", IsMember: true},
			{ID: "C01EVENT01", Name: "エージェントナイト-vol3", IsMember: true},
		},
		Users: map[string]slack.User{
			"U01HIKARI": sampleUser("U01HIKARI", "hikari", "星野 ひかり", "星野ひかり", "{{base}}/files/avatar-hikari.svg"),
			"U02REN":    sampleUser("U02REN", "ren", "若葉 蓮", "若葉レン", "{{base}}/files/avatar-ren.svg"),
			"U03SAKURA": sampleUser("U03SAKURA", "sakura", "三日月 さくら", "三日月さくら", "{{base}}/files/avatar-sakura.svg"),
			"U04DAICHI": sampleUser("U04DAICHI", "daichi", "天野 大地", "天野だいち", "{{base}}/files/avatar-daichi.svg"),
		},
		Emoji: map[string]string{
			"yatta":  "{{base}}/files/emoji-yatta.svg",
			"kansha": "{{base}}/files/emoji-kansha.svg",
		},
		Messages: []slack.Message{
			{
				Type: "message", Subtype: "channel_join",
				TS: ts(at(day1, 9, 0, 0)), User: "U01HIKARI",
				Text: "<@U01HIKARI>さんがチャンネルに参加しました",
			},
			{
				Type: "message", Subtype: "channel_join",
				TS: ts(at(day1, 9, 2, 0)), User: "U02REN", Inviter: "U01HIKARI",
				Text: "<@U02REN>さんがチャンネルに参加しました",
			},
			{
				Type: "message", Subtype: "channel_topic",
				TS: ts(at(day1, 9, 5, 0)), User: "U01HIKARI",
				Text: "<@U01HIKARI>さんがチャンネルのトピックを変更しました: エージェントナイト vol.3 準備 :robot_face:",
			},
			{
				Type: "message",
				TS:   ts(at(day1, 9, 12, 0)), User: "U01HIKARI",
				Text: "*エージェントナイト vol.3、開催決定です!* :tada:\n" +
					"開催日は *7月18日(金)* 、会場は前回と同じコワーキングスペースです。詳細は <https://example.com/wiki/agent-night-vol3|イベント wiki> にまとめていきます。\n" +
					"参加募集の告知は <#C00NEWS001|お知らせ> へ。質問はこのチャンネルか <@U02REN> まで。 <!here>",
				Reactions: []slack.Reaction{
					{Name: "tada", Count: 4},
					{Name: "yatta", Count: 2},
					{Name: "raised_hands", Count: 2},
				},
			},
			{
				Type: "message",
				TS:   ts(at(day1, 9, 30, 0)), User: "U02REN",
				Text: "今週の TODO です:\n" +
					"• ~会場の予約~ :white_check_mark:\n" +
					"• 募集ページ(`/events/vol3`)の公開\n" +
					"• LT 発表者募集のアナウンス\n" +
					"そのあと:\n" +
					"1. 配信リハーサル\n" +
					"2. 当日の役割分担決め",
				Edited:    editedAt(at(day1, 9, 47, 0)),
				Reactions: []slack.Reaction{{Name: "+1", Count: 3}},
			},
			{
				Type: "message", Subtype: "file_share",
				TS: ts(at(day1, 10, 15, 0)), User: "U03SAKURA",
				Text: "イベントバナーの初稿です :art: 感想もらえると嬉しいです!",
				Files: []slack.File{{
					ID:                 "F01BANNER",
					Name:               "バナー案-v1.svg",
					Mimetype:           "image/svg+xml",
					Size:               int64(len(assets["/files/banner-art.svg"].Body)),
					URLPrivateDownload: "{{base}}/files/banner-art.svg",
					Thumb360:           "{{base}}/files/banner-thumb.svg",
				}},
				Reactions: []slack.Reaction{
					{Name: "heart", Count: 3},
					{Name: "eyes", Count: 2},
				},
			},
			{
				Type: "message",
				TS:   ts(at(day1, 11, 2, 0)), User: "U04DAICHI",
				Text: "エージェントラボのこと、テックメディアで紹介されました :newspaper:\n<https://example.com/news/agent-lab>",
				Attachments: []slack.Attachment{{
					ServiceName: "サンプルテック",
					ServiceIcon: "{{base}}/files/news-icon.svg",
					Title:       "学生中心の AI エージェント勉強会「エージェントラボ」が拡大中",
					TitleLink:   "https://example.com/news/agent-lab",
					Text:        "AI エージェント活用の情報を交換するオープンなコミュニティとして、学生や若手エンジニアの参加が増えている。<@U03SAKURA>さんが手がけたイベントバナーも紹介された。",
					ImageURL:    "{{base}}/files/news-og.svg",
				}},
			},
			threadParent,
			{
				Type: "message",
				TS:   ts(at(day2, 11, 30, 0)), User: "U02REN",
				Text: "イベントサイト、staging へのデプロイまで通りました:\n" +
					"```$ agentlab deploy --target staging\nOK  build 412 (38s)\nOK  smoke tests 12/12```\n" +
					"本番反映はプログラム確定後に `agentlab deploy --target prod` を実行します。",
			},
			{
				Type: "message", Subtype: "bot_message",
				TS:    ts(at(day2, 11, 31, 0)),
				BotID: "B01DEPLOY", Username: "デプロイくん", BotProfile: botProfile("デプロイくん"),
				Text:      "*agent-night-site* v1.4.0 を staging に反映しました :package:",
				Reactions: []slack.Reaction{{Name: "kansha", Count: 2}},
			},
			{
				Type: "message", Subtype: "me_message",
				TS: ts(at(day2, 12, 20, 0)), User: "U04DAICHI",
				Text: "が当日配るステッカーを 100 枚印刷中",
			},
			{
				Type: "message", Subtype: "file_share",
				TS: ts(at(day2, 13, 5, 0)), User: "U01HIKARI",
				Text: "当日の運営マニュアル、最終版です :clipboard: スタッフのみなさんは目を通しておいてください。",
				Files: []slack.File{{
					ID:                 "F02RUNBOOK",
					Name:               "運営マニュアル.pdf",
					Mimetype:           "application/pdf",
					Size:               int64(len(assets["/files/unei-manual.pdf"].Body)),
					URLPrivateDownload: "{{base}}/files/unei-manual.pdf",
				}},
				Reactions: []slack.Reaction{{Name: "+1", Count: 2}},
			},
			{
				Type: "message", Subtype: "tombstone",
				TS: ts(at(day2, 14, 2, 0)),
			},
			{
				Type: "message",
				TS:   ts(at(day2, 15, 5, 0)), User: "U03SAKURA",
				Text: "今日はここまで。当日会えるのを楽しみにしています :sparkles:",
				Reactions: []slack.Reaction{
					{Name: "wave", Count: 3},
				},
			},
		},
		Replies: map[string][]slack.Message{
			threadTS: {
				threadParent,
				{
					Type: "message",
					TS:   ts(at(day2, 9, 44, 0)), ThreadTS: threadTS, User: "U02REN",
					Text: "タスク成功率は前回実装から *+12pt* :chart_with_upwards_trend: 内訳はこの下に貼ります",
				},
				{
					Type: "message", Subtype: "file_share",
					TS: ts(at(day2, 9, 51, 0)), ThreadTS: threadTS, User: "U03SAKURA",
					Text: "タスク別のスコアをグラフにしました:",
					Files: []slack.File{{
						ID:                 "F03CHART",
						Name:               "デモ評価結果.svg",
						Mimetype:           "image/svg+xml",
						Size:               int64(len(assets["/files/chart-eval.svg"].Body)),
						URLPrivateDownload: "{{base}}/files/chart-eval.svg",
						Thumb360:           "{{base}}/files/chart-thumb.svg",
					}},
					Reactions: []slack.Reaction{{Name: "kansha", Count: 2}},
				},
				{
					Type: "message",
					TS:   ts(at(day2, 10, 3, 0)), ThreadTS: threadTS, User: "U04DAICHI",
					Text: "&gt; タスク成功率は前回実装から +12pt\nこの数字、LT の冒頭スライドに載せましょう。<@U02REN> さん検証ありがとうございます!",
				},
				{
					Type: "message",
					TS:   ts(at(day2, 10, 10, 0)), ThreadTS: threadTS, User: "U01HIKARI",
					Text: "ではデモはこの構成で確定します。おつかれさまでした! :tada:",
				},
			},
		},
		Assets: assets,
	}
}
