package main

import (
	"time"

	"github.com/kiyohara/slapex/internal/slack"
)

// scenarioJA is the Japanese sample: the fictional trading company コスモ商事
// prepares the launch of a new candy product. Every name, user and asset is
// invented for this fixture; nothing comes from a real workspace.
//
// Pattern coverage: system messages (join / invited join / topic), mrkdwn
// decorations (bold / strike / inline code / code block / quote / lists /
// labeled and bare links / user / channel / @here mentions), standard and
// custom emoji, reactions, an edited message, a thread with four
// participants, an inline image upload, a URL unfurl with preview image, a
// PDF attachment, a bot message, a /me message and a deleted (tombstone)
// message.
func scenarioJA(now time.Time) *scenario {
	day1 := now.AddDate(0, 0, -2)
	day2 := now.AddDate(0, 0, -1)

	assets := map[string]sampleAsset{
		"/files/workspace-icon.svg": workspaceIconSVG("#0b7285", "#1971c2"),
		"/files/avatar-hikari.svg":  avatarSVG("ひ", "#e8590c"),
		"/files/avatar-ren.svg":     avatarSVG("レ", "#1971c2"),
		"/files/avatar-sakura.svg":  avatarSVG("さ", "#0ca678"),
		"/files/avatar-daichi.svg":  avatarSVG("だ", "#7048e8"),
		"/files/emoji-yatta.svg":    badgeEmojiSVG([]string{"やった"}, "#f08c00", 19),
		"/files/emoji-kansha.svg":   badgeEmojiSVG([]string{"感謝"}, "#e03131", 26),
		"/files/package-art.svg":    packageArtSVG("流星グミ", "ソーダ味 / コスモ商事"),
		"/files/package-thumb.svg":  packageArtSVG("流星グミ", "ソーダ味 / コスモ商事"),
		"/files/chart-shishoku.svg": chartSVG("試食会アンケート(100点満点)", []string{"味", "食感", "パッケージ", "価格"}, []int{92, 88, 95, 74}, "#845ef7"),
		"/files/chart-thumb.svg":    chartSVG("試食会アンケート(100点満点)", []string{"味", "食感", "パッケージ", "価格"}, []int{92, 88, 95, 74}, "#845ef7"),
		"/files/news-icon.svg":      serviceIconSVG("サ", "#c92a2a"),
		"/files/news-og.svg":        ogImageSVG("SAMPLE NEWS", "コスモ商事、夏の新作「流星グミ」を予告", "#343a40", "#1d2b53"),
		"/files/hatsubai-tejun.pdf": samplePDF([]string{
			"Ryusei Gumi - Launch Day Runbook (sample)",
			"1. Open the pop-up booth at 09:00",
			"2. Restock the shelves every 2 hours",
			"3. Share photos in the launch channel",
			"Generated by the slapex sample fixture",
		}),
	}

	threadTS := ts(at(day2, 9, 40, 0))
	threadParent := slack.Message{
		Type:       "message",
		TS:         threadTS,
		ThreadTS:   threadTS,
		User:       "U01HIKARI",
		Text:       "試食会の結果が出ました。詳細はこのスレッドにまとめます :thread:",
		ReplyCount: 4,
		Reactions:  []slack.Reaction{{Name: "eyes", Count: 3}},
	}

	return &scenario{
		Lang:        "ja",
		ChannelName: "流星グミ-発売準備",
		Auth: slack.AuthTest{
			URL:    "https://cosmo-shoji.example.slack.com/",
			Team:   "コスモ商事",
			TeamID: "TCOSMO001",
			User:   "slapex",
			UserID: "USLAPEX01",
			BotID:  "BSLAPEX01",
		},
		TeamInfo: &slack.TeamInfo{
			ID:     "TCOSMO001",
			Name:   "コスモ商事",
			Domain: "cosmo-shoji",
			Icon:   slack.TeamIcon{Image68: "{{base}}/files/workspace-icon.svg"},
		},
		Channels: []slack.Channel{
			{ID: "C00ZENTAI1", Name: "全体連絡", IsMember: true},
			{ID: "C01RYUSEI1", Name: "流星グミ-発売準備", IsMember: true},
		},
		Users: map[string]slack.User{
			"U01HIKARI": sampleUser("U01HIKARI", "hikari", "星野 ひかり", "星野ひかり", "{{base}}/files/avatar-hikari.svg"),
			"U02REN":    sampleUser("U02REN", "ren", "若葉 蓮", "若葉レン", "{{base}}/files/avatar-ren.svg"),
			"U03SAKURA": sampleUser("U03SAKURA", "sakura", "三日月 さくら", "三日月さくら", "{{base}}/files/avatar-sakura.svg"),
			"U04DAICHI": sampleUser("U04DAICHI", "daichi", "天野 大地", "天野だいち", "{{base}}/files/avatar-daichi.svg"),
		},
		Emoji: map[string]string{
			"yatta":  "{{base}}/files/emoji-yatta.svg",
			"kansha": "{{base}}/files/emoji-kansha.svg",
		},
		Messages: []slack.Message{
			{
				Type: "message", Subtype: "channel_join",
				TS: ts(at(day1, 9, 0, 0)), User: "U01HIKARI",
				Text: "<@U01HIKARI>さんがチャンネルに参加しました",
			},
			{
				Type: "message", Subtype: "channel_join",
				TS: ts(at(day1, 9, 2, 0)), User: "U02REN", Inviter: "U01HIKARI",
				Text: "<@U02REN>さんがチャンネルに参加しました",
			},
			{
				Type: "message", Subtype: "channel_topic",
				TS: ts(at(day1, 9, 5, 0)), User: "U01HIKARI",
				Text: "<@U01HIKARI>さんがチャンネルのトピックを変更しました: 流星グミ 発売準備 :candy:",
			},
			{
				Type: "message",
				TS:   ts(at(day1, 9, 12, 0)), User: "U01HIKARI",
				Text: "*流星グミの発売準備、今日からスタートです!* :tada:\n" +
					"発売日は *7月18日(金)* 。資料は <https://example.com/wiki/ryusei-gumi|発売準備 wiki> にまとめていきます。\n" +
					"全社向けの告知は <#C00ZENTAI1|全体連絡> へ。質問はこのチャンネルか <@U02REN> まで。 <!here>",
				Reactions: []slack.Reaction{
					{Name: "tada", Count: 4},
					{Name: "yatta", Count: 2},
					{Name: "raised_hands", Count: 2},
				},
			},
			{
				Type: "message",
				TS:   ts(at(day1, 9, 30, 0)), User: "U02REN",
				Text: "発売チェックリスト(第 1 週):\n" +
					"• ~パッケージ文言の最終確認~ :white_check_mark:\n" +
					"• `v0.9.3` の箱ラベル印刷手配\n" +
					"• 木曜の試食会の会場予約\n" +
					"そのあと:\n" +
					"1. 社内ドライラン\n" +
					"2. 本番リハーサル",
				Edited:    editedAt(at(day1, 9, 47, 0)),
				Reactions: []slack.Reaction{{Name: "+1", Count: 3}},
			},
			{
				Type: "message", Subtype: "file_share",
				TS: ts(at(day1, 10, 15, 0)), User: "U03SAKURA",
				Text: "パッケージデザインの初稿です :art: 感想ください!",
				Files: []slack.File{{
					ID:                 "F01PKG",
					Name:               "パッケージ案-v1.svg",
					Mimetype:           "image/svg+xml",
					Size:               int64(len(assets["/files/package-art.svg"].Body)),
					URLPrivateDownload: "{{base}}/files/package-art.svg",
					Thumb360:           "{{base}}/files/package-thumb.svg",
				}},
				Reactions: []slack.Reaction{
					{Name: "heart", Count: 3},
					{Name: "eyes", Count: 2},
				},
			},
			{
				Type: "message",
				TS:   ts(at(day1, 11, 2, 0)), User: "U04DAICHI",
				Text: "さっそく地元紙のオンライン版に載りました :newspaper:\n<https://example.com/news/ryusei-gumi>",
				Attachments: []slack.Attachment{{
					ServiceName: "サンプルニュース",
					ServiceIcon: "{{base}}/files/news-icon.svg",
					Title:       "コスモ商事、夏の新作「流星グミ」を予告",
					TitleLink:   "https://example.com/news/ryusei-gumi",
					Text:        "コスモ商事は今夏の新商品「流星グミ」を発表した。<@U03SAKURA>さんが手がけたパッケージデザインも話題を集めている。",
					ImageURL:    "{{base}}/files/news-og.svg",
				}},
			},
			threadParent,
			{
				Type: "message",
				TS:   ts(at(day2, 11, 30, 0)), User: "U02REN",
				Text: "特設サイト、staging へのデプロイまで通りました:\n" +
					"```$ cosmo deploy --target staging\nOK  build 412 (38s)\nOK  smoke tests 12/12```\n" +
					"本番反映はコンテンツ確定後に `cosmo deploy --target prod` を実行します。",
			},
			{
				Type: "message", Subtype: "bot_message",
				TS:    ts(at(day2, 11, 31, 0)),
				BotID: "B01DEPLOY", Username: "デプロイくん", BotProfile: botProfile("デプロイくん"),
				Text:      "*ryusei-gumi-site* v1.4.0 を staging に反映しました :package:",
				Reactions: []slack.Reaction{{Name: "kansha", Count: 2}},
			},
			{
				Type: "message", Subtype: "me_message",
				TS: ts(at(day2, 12, 20, 0)), User: "U04DAICHI",
				Text: "が発売日のチラシを 500 部印刷中",
			},
			{
				Type: "message", Subtype: "file_share",
				TS: ts(at(day2, 13, 5, 0)), User: "U01HIKARI",
				Text: "発売当日の手順書、最終版です :clipboard: 印刷して売り場の備品ボックスに入れておいてください。",
				Files: []slack.File{{
					ID:                 "F02RUNBOOK",
					Name:               "発売手順書.pdf",
					Mimetype:           "application/pdf",
					Size:               int64(len(assets["/files/hatsubai-tejun.pdf"].Body)),
					URLPrivateDownload: "{{base}}/files/hatsubai-tejun.pdf",
				}},
				Reactions: []slack.Reaction{{Name: "+1", Count: 2}},
			},
			{
				Type: "message", Subtype: "tombstone",
				TS: ts(at(day2, 14, 2, 0)),
			},
			{
				Type: "message",
				TS:   ts(at(day2, 15, 5, 0)), User: "U03SAKURA",
				Text: "今日はここまで。明日はリハーサルでお会いしましょう :sparkles:",
				Reactions: []slack.Reaction{
					{Name: "wave", Count: 3},
				},
			},
		},
		Replies: map[string][]slack.Message{
			threadTS: {
				threadParent,
				{
					Type: "message",
					TS:   ts(at(day2, 9, 44, 0)), ThreadTS: threadTS, User: "U02REN",
					Text: "総合満足度は前回試作から *+12pt* :chart_with_upwards_trend: 内訳はこの下に貼ります",
				},
				{
					Type: "message", Subtype: "file_share",
					TS: ts(at(day2, 9, 51, 0)), ThreadTS: threadTS, User: "U03SAKURA",
					Text: "アンケート結果をグラフにしました:",
					Files: []slack.File{{
						ID:                 "F03CHART",
						Name:               "試食会アンケート.svg",
						Mimetype:           "image/svg+xml",
						Size:               int64(len(assets["/files/chart-shishoku.svg"].Body)),
						URLPrivateDownload: "{{base}}/files/chart-shishoku.svg",
						Thumb360:           "{{base}}/files/chart-thumb.svg",
					}},
					Reactions: []slack.Reaction{{Name: "kansha", Count: 2}},
				},
				{
					Type: "message",
					TS:   ts(at(day2, 10, 3, 0)), ThreadTS: threadTS, User: "U04DAICHI",
					Text: "&gt; 総合満足度は前回試作から +12pt\nこの数字、LP にそのまま載せましょう。<@U02REN> さん集計ありがとうございます!",
				},
				{
					Type: "message",
					TS:   ts(at(day2, 10, 10, 0)), ThreadTS: threadTS, User: "U01HIKARI",
					Text: "では味は現行レシピで確定します。おつかれさまでした! :tada:",
				},
			},
		},
		Assets: assets,
	}
}
